version: '3.4'

services:
  django:
    image: django-sad
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./docs:/root/docs
    command: python3 manage.py runserver 0.0.0.0:8000