name: 5-matrixCI
on: [push]
jobs:
  integration:
    runs-on: ubuntu-20.04
    strategy:
      # if true, when job die, other will die. "operation cancelled."
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.2]
    steps:
      - name: Clone Reposistory
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: |
          python3 -m pip install --upgrade pip
          pip3 install django==4.0.2
          pip3 install gunicorn==20.1.0
      - name: Automate test
        run: |
          python3 manage.py test
        working-directory: ./docs